export const FEATURED_COLLECTIONS_FETCH_START = 'FEATURED_COLLECTIONS_FETCH_START';
export const FEATURED_COLLECTIONS_FETCH_SUCCESS = 'FEATURED_COLLECTIONS_FETCH_SUCCESS';
export const FEATURED_COLLECTIONS_FETCH_ERROR = 'FEATURED_COLLECTIONS_FETCH_ERROR';