export const FEATURED_COLLECTIONS_FETCH_START = 'FEATURED_COLLECTIONS_FETCH_START';
export const FEATURED_COLLECTIONS_FETCH_SUCCESS = 'FEATURED_COLLECTIONS_FETCH_SUCCESS';
export const FEATURED_COLLECTIONS_FETCH_ERROR = 'FEATURED_COLLECTIONS_FETCH_ERROR';

export const PHOTOS_FETCH_START = 'PHOTOS_FETCH_START';
export const PHOTOS_FETCH_SUCCESS = 'PHOTOS_FETCH_SUCCESS';
export const PHOTOS_FETCH_ERROR = 'PHOTOS_FETCH_ERROR';
